DECLARE
    CNT INTEGER;
BEGIN
    SELECT COUNT(*) INTO CNT FROM ALL_TABLES WHERE OWNER = 'SCM_RJ_SIMP' AND TABLE_NAME = 'ALERT_RULE';
    IF CNT > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE SCM_RJ_SIMP.ALERT_RULE CASCADE CONSTRAINTS';
    END IF;
END;
/

CREATE TABLE SCM_RJ_SIMP.ALERT_RULE (
    ID                INT IDENTITY(1,1) PRIMARY KEY,
    NAME              VARCHAR(64) NOT NULL,
    DESCRIPTION       VARCHAR(255) DEFAULT '',
    LOG_TYPE          TINYINT NOT NULL,
    RULE_TYPE         TINYINT NOT NULL,
    LEVEL             TINYINT DEFAULT NULL,
    LINK_TYPE         TINYINT DEFAULT 0,
    CONDITIONS        TEXT DEFAULT NULL,
    COMBINE_DURATION  INT DEFAULT NULL,
    COMBINE_COUNT     INT DEFAULT NULL,
    COMBINE_RULE_ID   INT DEFAULT NULL,
    WHITELIST_ID      INT DEFAULT NULL,
    BLACKLIST_ID      INT DEFAULT NULL,
    STATUS            TINYINT DEFAULT 1,
    CREATE_TIME       BIGINT NOT NULL,
    UPDATE_TIME       BIGINT NOT NULL,
    IS_DELETE         TINYINT DEFAULT 0
);

COMMENT ON TABLE SCM_RJ_SIMP.ALERT_RULE IS '告警规则表';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.NAME IS '规则名称';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.DESCRIPTION IS '描述';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.LOG_TYPE IS '日志类型: 0=平台登录日志, 1=IM登录日志, 2=DLP日志';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.RULE_TYPE IS '规则类型: 0=普通规则, 1=组合规则';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.LEVEL IS '普通规则告警等级: 1=一级红, 2=二级橙, 3=三级黄';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.LINK_TYPE IS '关联方式: 0=与, 1=或';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.CONDITIONS IS '匹配条件 JSON';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.COMBINE_DURATION IS '组合规则时间窗口(分钟), 预留';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.COMBINE_COUNT IS '组合规则触发次数阈值';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.COMBINE_RULE_ID IS '组合规则引用的普通规则 ID';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.WHITELIST_ID IS '白名单 ID';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.BLACKLIST_ID IS '黑名单 ID';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.STATUS IS '状态: 0=禁用, 1=启用';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_RULE.IS_DELETE IS '软删除: 0=未删, 1=已删';
