-- =====================================================
-- 告警黑白名单 建表脚本 (DM8 达梦, 大小写敏感)
-- DM8 大小写敏感模式下，表名/字段名使用大写。
-- 表创建在 SCM_RJ_SIMP 模式下。
-- =====================================================

CREATE TABLE SCM_RJ_SIMP.ALERT_ACCESS_LIST (
    ID            INT             NOT NULL IDENTITY(1,1),
    NAME          VARCHAR(64)     NOT NULL,
    TYPE          TINYINT         NOT NULL,
    STATUS        TINYINT         DEFAULT 1 NOT NULL,
    REMARK        VARCHAR(255),
    CREATE_TIME   BIGINT          NOT NULL,
    UPDATE_TIME   BIGINT          NOT NULL,
    IS_DELETE     TINYINT         DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE SCM_RJ_SIMP.ALERT_ACCESS_LIST IS '告警黑白名单';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_ACCESS_LIST.ID IS '主键';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_ACCESS_LIST.NAME IS '规则名称';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_ACCESS_LIST.TYPE IS '类别: 0=白名单, 1=黑名单';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_ACCESS_LIST.STATUS IS '状态: 0=禁用, 1=启用';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_ACCESS_LIST.REMARK IS '备注';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_ACCESS_LIST.CREATE_TIME IS '创建时间(13位时间戳)';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_ACCESS_LIST.UPDATE_TIME IS '更新时间(13位时间戳)';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_ACCESS_LIST.IS_DELETE IS '软删除: 0=未删, 1=已删';

CREATE TABLE SCM_RJ_SIMP.ALERT_ACCESS_LIST_USER (
    ID             INT            NOT NULL IDENTITY(1,1),
    LIST_ID        INT            NOT NULL,
    USER_NAME      VARCHAR(64)    NOT NULL,
    USER_ACCOUNT   VARCHAR(64)    NOT NULL,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE SCM_RJ_SIMP.ALERT_ACCESS_LIST_USER IS '黑白名单用户明细';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_ACCESS_LIST_USER.ID IS '主键';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_ACCESS_LIST_USER.LIST_ID IS '黑白名单ID';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_ACCESS_LIST_USER.USER_NAME IS '用户名';
COMMENT ON COLUMN SCM_RJ_SIMP.ALERT_ACCESS_LIST_USER.USER_ACCOUNT IS '账号';

CREATE INDEX IDX_ALERT_ACCESS_LIST_USER_LIST_ID
    ON SCM_RJ_SIMP.ALERT_ACCESS_LIST_USER (LIST_ID);
